Assuming unrestricted shared filesystem usage.
None
host: Biswajit
Building DAG of jobs...
Provided cores: 8
Rules claiming more threads will be scaled down.
Job stats:
job                             count
----------------------------  -------
all                                 1
checking_gaps                       1
inspect_defaulting_companies        1
total                               3

Select jobs to execute...
Execute 2 jobs...
[Wed May  7 17:54:25 2025]
localrule inspect_defaulting_companies:
    input: Data/bankruptcy_filings/bankruptcy_filings_cleaned.csv, Data/financials/financials_annual.gz
    output: Results/initial_inspection/defaulting_companies_year.csv, Results/initial_inspection/yearly_cases_default.csv
    jobid: 2
    reason: Code has changed since last execution
    resources: tmpdir=C:\Users\biswa\AppData\Local\Temp

[Wed May  7 17:54:25 2025]
localrule checking_gaps:
    input: Data/financials/financials_annual.gz
    output: Results/initial_inspection/companies_with_gaps.csv, Results/initial_inspection/gapcount.csvResults/initial_inspection/percent_no_gap.csv
    jobid: 3
    reason: Missing output files: Results/initial_inspection/companies_with_gaps.csv, Results/initial_inspection/gapcount.csvResults/initial_inspection/percent_no_gap.csv
    resources: tmpdir=C:\Users\biswa\AppData\Local\Temp

RuleException:
CalledProcessError in file "C:\Users\biswa\DefaultRiskValuation\Snakefile", line 41:
Command 'C:/Users/biswa/anaconda3/envs/snakemake/python.exe "C:\Users\biswa\DefaultRiskValuation\.snakemake\scripts\tmpgoi0au80.inspect_defaulting_companies.py"' returned non-zero exit status 1.
[Wed May  7 17:54:51 2025]
Error in rule inspect_defaulting_companies:
    message: None
    jobid: 2
    input: Data/bankruptcy_filings/bankruptcy_filings_cleaned.csv, Data/financials/financials_annual.gz
    output: Results/initial_inspection/defaulting_companies_year.csv, Results/initial_inspection/yearly_cases_default.csv
Terminating processes on user request, this might take some time.
RuleException:
CalledProcessError in file "C:\Users\biswa\DefaultRiskValuation\Snakefile", line 30:
Command 'C:/Users/biswa/anaconda3/envs/snakemake/python.exe "C:\Users\biswa\DefaultRiskValuation\.snakemake\scripts\tmpblo08_4i.checking_gaps.py"' returned non-zero exit status 1.
[Wed May  7 17:54:51 2025]
Error in rule checking_gaps:
    message: None
    jobid: 3
    input: Data/financials/financials_annual.gz
    output: Results/initial_inspection/companies_with_gaps.csv, Results/initial_inspection/gapcount.csvResults/initial_inspection/percent_no_gap.csv
Complete log(s): C:\Users\biswa\DefaultRiskValuation\.snakemake\log\2025-05-07T175425.799015.snakemake.log
WorkflowError:
At least one job did not complete successfully.
